example_app/urls.py
from django.urls import path 
from . import views 

# define app configuration name 
app_name = 'example_app'

# map views to URL configurations 
urlpatterns = [
    path("index", views.index, name="index"),
    path("greet", views.greet, name="greet")
]

example_project/urls.py
from django.contrib import admin

# remember to import include!
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("example_app.urls"))
]

example_app/models.py
from django.db import models

# Create your models here.
class Students(models.Model): 
    gnum = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100) 

    def __str__ (self): 
        return f"G{self.gnum}: {self.name}"

example_app/views.py
from django.shortcuts import render

# import Django HttpResponse library 
from django.http import HttpResponse 

# import Django forms library 
from django import forms 

# import Django redirect library
from django.shortcuts import redirect

from django.db import models
from .models import Students

# define our Form class 
class NewForm(forms.Form):
    name = forms.CharField(label="Enter Name")

# define a "view" 
def index(request): 
    return render(request, "example_app/index.html", {'form':NewForm()})

def greet(request): 
    if request.method == 'POST': 
        form = NewForm(request.POST)
        if form.is_valid(): 
            name = form.cleaned_data['name']
            student = Students.objects.create(name=name)
            return render(request, "example_app/greet.html", {'students':Students.objects.all()})

    return redirect(index)

example_app/templates/example_app/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greeting</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'example_app/styles.css' %}">

</head>
<body>
    <ul>
        {% for student in students %}
        <li>{{ student.gnum }}: {{student.name}} </li>
        {% endfor %}
    </ul>
</body>
</html>

example_app/templates/example_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>


    {% load static %}
    <link rel="stylesheet" href="{% static 'example_app/styles.css' %}">

</head>
<body>
    <form action="{% url 'example_app:greet' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>